materializecss/materialize

- js/dropdown.js
Correction of the calculation of the position of the dropdown when the coverTrigger option is false and the dropdown is near the bottom of the window.
This PR fixes issue #6279, related to the position of the dropdown of the autocomplete component.
reference: https://github.com/Dogfalo/materialize/pull/6498 by @RaquelAM
> fix dropdown position when coverTrigger is false

- sass/components/forms/_switches.scss
There's a style problem when a switch disabled but checked, the background color should be disabled color, not enabled color.
[Reference design](https://material.angularjs.org/latest/demo/switch)
[Problem example](https://codepen.io/smankusors/full/dKBPxg)
Note : This is from https://github.com/Dogfalo/materialize/pull/6021
> Fix disabled checked switch style

- js/waves.js
- sass/components/_waves.scss
Waves.js library was outdated.
See #5779, #5472 and #3153
This is 99% original Waves.js code. (See: [v0.7.6](https://github.com/fians/Waves/blob/v0.7.6/dist/waves.js))
Changes:
- Initialization on Dom Load
- Passiv Event Listeners
- Custom Colors
I am using this in my application for quite some time, seams to work fine.
Moved from https://github.com/Dogfalo/materialize/pull/6060
> Upgrade waves

- jade/page-contents/chips_content.html
- js/chips.js
* this is an implementation of https://github.com/Dogfalo/materialize/pull/5725
* added boolean option autoCompleteOnly to chips defaults options
* when pressing enter to add a chip, the chip is only added if M.Chips.options.autocompleteOnly==false (or if hasAutcomplete == false)
> Chips autocomplete should have option to prevent user own input

- js/chips.js
This is a re-implementation of https://github.com/Dogfalo/materialize/pull/6324.
Original problem statement:
_If you have focused on a chip and then un-focus the entire browser window (not focusing on another element) the \_handleChipsBlur function is executed. This sets null in \_selectedChip but when you return to the window the chip retains its focus. If you try to hit the left, right and delete keys nothing is executed (in delete an exception is thrown)._
* This fix checks for document.hidden and does not unselect the chip if the document is in fact hidden.
* For notes on compatibility, it looks like IE11 supports document.hidden
* https://caniuse.com/?search=Page%20Visibility
* Also introduces a minor update that focuses the input element when deleting the last chip.
> revert blur and focus on last chip delete

- jade/_footer.html
- jade/page-contents/tooltips_content.html
- js/tooltip.js
Currently using this library for [NiM](https://github.com/june07/NiM) and would like to keep transparent tooltips as seen here:
This small change adds the ability to change tooltip default opacity using options.  The ultimate result are tooltips that can be transparent.
```
M.Tooltip.init(tooltipElement, {
_animateInOpacity: 0.7
})
```
> Added ability to change tooltip animate opacity.

- CONTRIBUTING.md
- README.md
Developers don't need to install grunt-cli because we already installed into node_modules via `npm install`. Now, I replaced commands in docs using `npm` instead of `grunt`.
> Update docs to avoid installing grunt-cli

- package-lock.json
- package.json
`npm install` succeeds with Node.js 8.x. But, its support has already ended.
This PR allows `npm install` with Node.js 10.x, 12.x, and 14.x.
Please see, https://www.npmjs.com/package/node-sass
> Supported Node.js versions vary by release
We are using node-sass v4.7.2, so the following error appears when `npm install` with Node.js 10 and above.
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.7.2 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.7.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
lint-staged says "lint-staged requires at least version 6 of Node, please upgrade" and we cannot commit while using Node.js 10 and above. This is a bug …
> Support Node.js 10 and above (Update node-sass and lint-staged)

- README.md
Changed cdn in quickstart to use materializecss, not dogfalo. This means that if someone uses the cdn suggested in the quickstart, they get all the new stuff from this repo, not the old repo.
> Updated quickstart cdn

- Gruntfile.js
When exec the release script `npx grunt release --oldver=1.0.0 --newver=1.0.1`, grunt accidentally replaced `"grunt-contrib-jade": "^1.0.0"` to `"grunt-contrib-jade": "^1.0.1"`. This behavior can cause a problem, so I fixed it to replace the strings appropriately. Additionally, I removed `replace:readme` task because the description of "Current Version : " has already disappeared from README.
> Fix Gruntfile.js to prevent erroneous replace

- sass/components/_chips.scss
After the change of https://github.com/Dogfalo/materialize/pull/6313, the weird underline appears on the input field. This PR fixes the problem while preserving the behavior of the `browser-default` class.
> Fix the style of the input field for chips

- README.md
- package.json
Added a description of how to build. It will help many developers who wants to get the latest materialize.css or materialize.js.
I'm not good at English, so please fix more natural if you feel something wrong.
> Update readme to describe building

- sass/components/_sidenav.scss
This PR reverts commit bafde665e7b600fc273d0b00596aa52860109206 because it breaks sidenav style.
It is better to understand the motivation for his change, but I don't have any way because this commit doesn't associated to any issues or pull requests, so I decided to simply revert.
> Revert "Refactored sidenav css to accommodate btns better"

- sass/components/_modal.scss
In Safari (both iOS and macOS), if `modal-content` is vertically longer than `modal`, tapping underside the modal area could not close the modal. This PR fixes the problem by specifying overflow-y of `modal-content`.
> Fix modal behavior in Safari

- js/global.js
- js/sidenav.js
Marked the touchmove event handler as 'passive' on [sidenav.js](https://github.com/materializecss/materialize/blob/v1-dev/js/sidenav.js) to make the page more responsive, as per chrome console violation error:
_materialize.min.js?ver=1.0.0:6 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952_
Unfortunately I do not know how to do testing, so have left it unchecked.
> fixed passive scroll listener for sidenav

- jade/page-contents/text_inputs_content.html
- sass/components/_chips.scss
- sass/components/forms/_input-fields.scss
- sass/components/forms/_select.scss
* Implements https://github.com/Dogfalo/materialize/pull/2490 to have text input suffix icons.
* That PR was issued under what appears to be an older version of the code so there isn't much that is similar between this PR and that one.
> add support for text input suffix icons

- docs/js/search.js
- jade/feature-discovery.jade
Here I propose about improving search results. So instead of search result ends with ".html", which IMO not good, I improved it with new format "[category, if any] > [document title]". I also added additional tags (previously it written as "title") that hopefully will produce better search results.
> [DOC] Improved Search Results

- jade/page-contents/autocomplete_content.html
- js/autocomplete.js
* This PR implements https://github.com/Dogfalo/materialize/pull/6602 to enable the autocomplete component to take dropdown options.
* Note: This does not implement the styling piece of that PR which alters the dropdown style if the container is `document.body`.
* This is also mentioned on the list of PRs to merge and in https://github.com/materializecss/materialize/issues/35.
> enable autocomplete to accept dropdown options

- sass/components/_sidenav.scss
There's additional 60px because it's problem with mobile devices. Without it, when hiding the address bar, there's some kind of jumpy effect, or rather re-rendering effect that makes UX not really smooth. But this fix comes with another issue, see https://github.com/Dogfalo/materialize/issues/4719. It's fixed on mobile. But in desktop, the scrollbar doesn't look good.
So, instead of using `calc(100% + 60px)`, I think using `100vh` is more appropriate. Here is an [article](https://developers.google.com/web/updates/2016/12/url-bar-resizing) explaining this.
I also deleted a temporary fix (I can't find the documentation about `-moz-calc` thing)
I hope this didn't create another new issue... so tell me if you found one 😉 
Before : https://codepen.io/smankusors/pen/VwKdwPG
After : …
> Fixed overflowed scroll sidenav on desktop

- .github/workflows/nightly.yml
Uses Github Actions (#17) to build on new commits and weekly (in case there are no new commits). Here's an example run: https://github.com/ChildishGiant/materialize/actions/runs/476340135 
The workflow's very simple, it just runs all tests, builds and then uploads the build. 
There's currently no simple way of linking users to the latest build (https://github.com/actions/upload-artifact/issues/52) but it's something for the people waiting on nightly builds (Ping for those in #13). We could link to [nightly.link](https://nightly.link/) in the meantime (https://nightly.link/ChildishGiant/materialize/workflows/nightly/GHA/build) or the equivalent for this repo
> Nightly builds

- jade/page-contents/autocomplete_content.html
- jade/page-contents/toasts_content.html
- jade/page-contents/tooltips_content.html
- js/autocomplete.js
- js/toasts.js
- js/tooltip.js
- test/html/autocomplete.html
- test/html/toast.html
- test/html/tooltip.html
This should deal with the open CVEs referenced in #38, Dogfalo#6286, and Dogfalo#6331
- Add the options `text` and `unsafeHTML`
- Change behavior of the `data-tooltip` attribute to set the `text` property instead of `html` **(breaking change)**
- Inject `text` as `.textContent`
- Append `html/unsafeHTML` as HTML
- If `unsafeHTML` is used, `html` will be ignored
- Updated docs to indicate that use of `html` is deprecated, and added warnings to `unsafeHTML`
- Add the options `text` and `unsafeHTML`
- Inject `text` as `.textContent`
- Append `html/unsafeHTML` as HTML
- If `unsafeHTML` is used, `html` will be ignored
- Updated docs to indicate that use of `html` is deprecated, and added warnings to `unsafeHTML`
- Add `allowUnsafeHTML` option defaulting to `false`
- If user sets …
> Fixes open vulnerabilities for #38

- js/autocomplete.js
- js/dropdown.js
- tests/spec/autocomplete/autocompleteSpec.js
This is a bugfix for #93 
As a part of this PR I make autocomplete options independent between instances
Also there is a fix in `dropdown.js : _moveDropdown`, which avoids adding a component to the same parent twice (it caused tests to fail, since on the second append a child was removed from a parent)
> #93 fixed sharing onOptionClick handler in multiple autocomplete instances

- js/autocomplete.js
- js/dropdown.js
Dropdown and autocomplete now smoothly scrolls to elements selected with keyboard (Closes #12)
Here's a before and after:
https://user-images.githubusercontent.com/13716824/112668270-3906a300-8e56-11eb-93e3-cd9e7a1b640c.mp4
https://user-images.githubusercontent.com/13716824/112668352-52a7ea80-8e56-11eb-8446-efa063cf109b.mp4
You can see I made it smooth scroll as the jumping about that was previously used can be a bit jarring.
Debatable since the current implementation was disabled for autocompletes because it didn't work.
> feat(dropdown): ♿  improve dropdown & autocomplete a11y

- js/toasts.js
- js/tooltip.js
- test/html/tooltip.html
This would add a warning when using the now deprecated html setting.
> feat: :wastebasket: add warning when using deprecated html setting

- js/select.js
A fix provided in Dogfalo/materialize#6142 to fix Dogfalo/materialize#3249
CC of said PR:
> ## Proposed changes
> 
> Fixes #3249.
> ## Screenshots:
> 
> Code:
> 
> ```
> <option>
>     Nachmittag
> </option>
> ```
> 
> Before:
> ![screenshot_2018-09-28 youtube-adventskalender 1](https://user-images.githubusercontent.com/4778485/46182301-46656580-c2cb-11e8-9ca6-794b0db8b1d8.png)
> 
> After:
> ![screenshot_2018-09-28 youtube-adventskalender](https://user-images.githubusercontent.com/4778485/46182302-47969280-c2cb-11e8-80f5-c4c5eea89c0a.png)
> ## Types of changes
> 
> * [x]  Bug fix (non-breaking change which fixes an issue).
> * [ ]  New feature (non-breaking change which adds functionality).
> * [ ]  Breaking change (fix or feature that would cause existing functionality to change).
> 
> …
> Trim select text

- docs/js/init.js
- jade/getting_started/getting_started_content.html
Hello! So glad to see Materialize is still being maintained. I use the framework frequently. I thought it would be much easier to grab the CDN if there was a 'copy code' button.
I saw that the issue was also brought up here - https://github.com/Dogfalo/materialize/issues/6611#issue-731825880
It took a bit of digging to put together code that works, but I've added it here. I am more familiar with vanilla JS than jQuery so I opted to just add my code at the bottom of the init.js file. I am not sure what would be considered best practice for your codebase, so I'm open to feedback or suggestions. Thoughts: 1) It could of course be implemented for other code snippets across the site. 2) A tooltip or modal might work better than an alert [ edit: I changed this to a span, though some users may …
> add copy code button

- js/dropdown.js
This is another PR for Dogfalo#6279. The initial one is #4.
Original PR #4 fixes the alignment issue when there is not enough space **both** on the bottom and top sides.
This PR fixes the dropdown cover when there is not enough space at the bottom side, but still enough space at the top side (so scrolling is not needed).
_(top and bottow browser panels are part of screenshot, to demonstrate which size is available)_
> #6279: fixed aligning of dropdown with coverTrigger=false, when can align bottom

- js/tapTarget.js
Fix issue #97 Feature discovery moves element when activated by @ChildishGiant
> Fix issue with Feature Discovery

- js/select.js
> Fix bug by adding missing classes in img element in select component

- jade/getting_started/getting_started_content.html
> fix(doc): invalid download sass link

- jade/getting_started/getting_started_content.html
Reverts materializecss/materialize#128
> Revert "fix(doc): invalid download sass link"

- jade/page-contents/pickers_content.html
- js/datepicker.js
- js/timepicker.js
The datepicker and timepicker have containers that are specified in different ways (datepicker = element, timepicker = document query selector string). These changes allow both to have the container specified by either an element or a query string for both elements to maintain backward compatability while also harmonizing the entry method.
> Update datepicker & timepicker "container" option to allow being specified the same way

- pug/_navbar.pug
Dependant on #141 (how I've done it)
Currently the browser's default autocomplete can get in the way of our one:
I changed one line to stop that (Although it will seem like loads because it's comparing to master, not #141 )
> Autocomplete off for docs

- tests/spec/cards/cardsFixture.html
- tests/spec/sidenav/sidenavFixture.html
When running `npm test`, there's a warning shown below when testing Card and Sidenav plugin
```
log: Failed to load resource: net::ERR_FILE_NOT_FOUND
log: Failed to load resource: the server responded with a status of 403 (Forbidden)
```
This is happen when we merged #78, where the "images" folder moved to "docs" folder. This PR fixes the img src to the updated one. There's also one image on the card component that become missing (403 forbidden), so I replaced it with [sample-1.jpg](https://github.com/materializecss/materialize/blob/eb04cbfff7b523ee76167af1e2401c3d95762c8c/docs/images/sample-1.jpg).
> Fix ERR_FILE_NOT_FOUND when running npm test

- sass/components/_global.scss
Fix for issue #146 (Rounding artefacts with dark table row)
Tested with plain and striped tables.
> Fix for issue #146 (Rounding artefacts with dark table row)

- pug/_navbar.pug
Hello! Haven't had time to contribute in a while. I noticed the docs for 0.100.2 include a link back to the v1 beta docs. Clicking on that took me to materializecss.com, and I thought that was confusing since the latest ones on Github look very similar. I thought the best way to mitigate this issue was to open the older docs in a new window.
> open old docs in new window

- docs/js/init.js
- pug/getting_started/getting_started_content.html
- Use a single message container to inform user when text is copied.
- Copy text without creating a textarea. Currently, the textarea appears at the bottom of the page. Screenshot below.
> Copy text without creating textarea and use single container for copy success message

- js/datepicker.js
- pug/page-contents/pickers_content.html
- tests/spec/datepicker/datepickerFixture.html
- tests/spec/datepicker/datepickerSpec.js
This is described in #151. In short: This adds the ability to add a formatting function as format option to datepicker instance, which allows things like this:
```js
M.Datepicker.init(elems, {
format: date => new Intl.DateTimeFormat(locale).format(date)
});
```
> feat(datepicker): add possibility for a format function to Datepicker

- js/dropdown.js
- test/html/select.html
> fix(dropdown): 🐛 fix a bug with dropdown actives when used in selects

- CONTRIBUTING.md
In this PR I proposed to update the CONTRIBUTING.md doc. Here's the list I updated:
* improving ToC
* updating labels section
* mention convention commit format in PR guide
* removed translations section (we don't have any other languages in the docs)
I'm not sure about labels section. We haven't formally (?) arrange the labels that we created and used? Like which labels used on PR only, or issue only? Or what guideline for the `good first issue` label?
Please let me know if there's something wrong/missing. Edits are also welcome to improve this document and/or PR. 😉
Thanks,
> Improving CONTRIBUTING document

- docs/js/init.js
- pug/getting_started/getting_started_content.html
- pug/page-contents/autocomplete_content.html
- pug/page-contents/badges_content.html
- pug/page-contents/breadcrumbs_content.html
- pug/page-contents/buttons_content.html
- pug/page-contents/cards_content.html
- pug/page-contents/carousel_content.html
- pug/page-contents/checkboxes_content.html
- pug/page-contents/chips_content.html
- pug/page-contents/collapsible_content.html
- pug/page-contents/collections_content.html
- pug/page-contents/color_content.html
- pug/page-contents/css-transitions_content.html
- pug/page-contents/dropdown_content.html
- pug/page-contents/featureDiscovery_content.html
- pug/page-contents/floating-action-button-content.html
- pug/page-contents/footer_content.html
- pug/parallax/parallax_content.html
- sass/_style.scss
I've added the first run of 2 copy code icons to the Getting Started page. The Clipboard API doesn't seem to work locally but I imagine will work when we push the changes live. Here is a codepen of the changes for reference as well:
https://codepen.io/christinavoudouris/pen/oNWqYLK
If these look good, I can go ahead and add them throughout the site.
> docs: change to/add copy code icons

- pug/getting_started/getting_started_content.html
- templates/parallax-template/index.html
- templates/parallax-template/preview.html
Note: the updated templates might still have to be zipped up; I didn't have access to do this last time.
> add back templates section, fix stylesheet link in parallax template

- pug/about/about_content.html
- pug/index/index_content.html
- pug/page-contents/grid_content.html
- Added the community as part of the team, by explaining why we forked the repo and by adding a
dynamic image that show the top 24 contributors. Prob is that it don't sort by team members but
rather by commit numbers
- Added a message in the index page that says this version is a fork
- Changed the catchphrase in the homepage
- Rephrased a sentence inside the introduction grid shown in the homepage and grid section
fix #194
<details>
<summary>Click here to see screenshots & changes:</summary>
</details>
> docs: rework about and home page to mention this is the community fork

- pug/page-contents/select_content.html
rephrase the sentence about the need to call init to reload a dynamic select component
fix #171
docs
All fine
> docs(select): rephrase a sentence in select docs, issue 171

- js/select.js
- test/html/select.html
I improved the internal structure of the component, because I saw that there where no Array used for the Options.
So there are no visible changes for the users, but the code is working now internally better and faster.
This is the preperation of dynamically loading Options without reinitializing the Component. But I also thougt
about making the Select similiar to the Autocomplete and give a "data" Object which can then be rendered.
**Future Plan:**
This should also be done in the Autocomplete. In the Autocomplete it will be a breaking change.
I want to make a combination of the Autocomplete and the Multi-Select with dynamic Loading Data
because I need it for my own Project, but I saw that it was already multiple times requested by other users.
For Reference see issues here:
#219 
#67
#115 …
> Refactored Select internaly for Arrays to prepare for other changes

- FOR_MAINTAINERS.md
In this PR, I would like to propose a documentation for the maintainers. So that if I'm not available and/or someone else would like to move this forward in the future, at least we will know what should be done.
In this document, I added 3 sections, which is labels, releasing a new version, and generating a changelog.
Let me know what do you think about this.
> Add maintainers doc

- sass/components/_global.scss
Makes `striped` work for tables again, which is a fix for #279. Bug is described within the issue.
> Fix `striped` for tables. Fixes #279.

- pug/page-contents/buttons_content.html
Break up the first para, make minor changes, and place the contents under relevant sub-topics.  Add definition to floating action buttons based on https://material.io/archive/guidelines/components/buttons.html#.
> Update and rearrange content for readability

- js/forms.js
- tests/spec/forms/formsFixture.html
Ensure that floating labels work correctly on input elements without an explicit `type` attribute.
n/a
> fix: floating labels do not work when type attribute is absent from input element #288

- docs/js/init.js
- test/html/cards.html
- test/html/forms.html
- tests/spec/autocomplete/autocompleteSpec.js
- tests/spec/carousel/carouselFixture.html
fix #251
It seems that placehold.it has been cancelled. To get rid of the errors, I changed all to the matching API of placeholder.com
> fix(placeholder images): replace placehold.it with placeholder.com

- js/timepicker.js
- sass/components/_timepicker.scss
Following up [issue-118 Time Picker allow for typing input](https://github.com/materializecss/materialize/issues/118), I have added time input by typing functionality. The user can edit the time and minute on the digital clock directly while original functionality remains same. I have updated `/js/timepicker.js`. But I tested with `docs/js/materialize`. Please let me know if I picked up the wrong file. Once my direction is accepted, I will also add tests and update the documentation as well. And I would appreciate any feedback or other direction. I will quickly follow up.
> feat: add input function by typing to timepicker

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
I updated the PR template and the contributing doc, so that it's easier for the first time contributors and us reviewers when handling the conventional commits format. Let me know what do you guys think 😉 
(also merge two similiar checklist as one about change in docs)
n/a
> Make conventional commits more explicit

- .commitlintrc
- package-lock.json
- package.json
The Commit-Message was not checked properly for many contributers, due to an old or outdated version of Husky and Commitlint. I updated the package.json File and added a required Commitlint-File. It works now on my machine, i re-installed node_modules with the new packege.json File and it works now. I hope this prevents future issues with it.
Updated the version of Husky and Commitlint. Also tested on a windows machine.
> Update husky version

- Gruntfile.js
- package.json
As we are not using travis, #188 asked to rename it to something else (I renamed the task into `test`)
Runs fine with
> ci: remove mentions of Travis in the task files

- js/toasts.js
- pug/page-contents/toasts_content.html
- test/html/toast.html
- tests/spec/toast/toastSpec.js
Add "ARIA" attributes to Toast instances so as to enhance performance of assistive technologies (e.g.: screen readers).
In spite of not affecting existing projects, this commit must improve the component's overall accessibility concerns, since it gives toast elements "alert" attributes in addition to better semantics in code samples available in the docs.
> Toast accessibility

- .all-contributorsrc
- .github/workflows/docs.yml
- pug/about/about_content.html
Signed-off-by: CypherpunkSamurai <CypherpunkSamrai@users.noreply.github.com>
This PR adds CI changes to automatically update contributors list when generating documentation. This aims to fix #239
> Added CI to Automate Contributors list

- js/select.js
- pug/page-contents/select_content.html
- test/html/select.html
- tests/spec/select/selectSpec.js
Resolved some semantic issues in select component so as to enhance performance of assistive technologies (e.g.: screen readers).
In spite of not affecting existing projects, this PR must improve the component's overall accessibility concerns, since it fixes some HTML semantic issues (for assistive technologies) and improves keyboard navigation, in addition to better semantics in code samples available in the docs.
**Summary**:
- Add missing "ARIA" attributes to custom input, dropdown and list items:
- Fix HTML semantic roles by adding "combobox", "listbox" and "option" roles, respectively;
- Custom input element is now "read-only" for screen readers as well;
- Custom input element "controls" dropdown;
- Improved element hierarchy to assistive technologies by adding references to …
> Select accessibility

- package-lock.json
- package.json
Add pinst to disable postinstall hook while packaging to fix install errors... fixes #310
> fix: remove postinstall hook from packed package

- js/select.js
Assign "aria-required" attribute to input element rather than options dropdown.
Select elements with "required" attribute are now correctly recognized by assistive technologies.
**NB:** No "visual" changes must take place and no additional "test cases" seems to be necessary.
> fix(select): misplaced aria-required attribute

- pug/page-contents/dropdown_content.html
Added Example for dropdown alignment option
This PR adds documentation changes. New example for `alignment` option of dropdown component was added in dropdown documentation. This PR aims to fix #275 (More Examples for Dropdown alignment)
> Added Example for alignment option

- js/dropdown.js
In case the `body` or `html` element defines a `overflow` other than `visible`, drop-downs are currently misplaced.
As both elements are not relevant when trying to look for the best placement, this PR adds a check to ignore them.
Fixes https://github.com/materializecss/materialize/issues/311
see https://github.com/materializecss/materialize/issues/311
> Improve drop-down placement

- js/slider.js
- pug/page-contents/media_content.html
- sass/components/_slider.scss
- test/html/slider.html
- tests/spec/slider/sliderFixture.html
- tests/spec/slider/sliderSpec.js
Enhanced accessibility performance of Materialize's Slider component by adding proper ARIA attributes and better support to keyboard navigation.
Following [W3C's accessible carousel example](https://www.w3.org/WAI/tutorials/carousels/), some new accessibility features have been implemented:
- Pause transition on mouve hover: It is possible to disable this default behaviour by setting "pauseOnHover" option to "false";
- Pause transition on focus (generally triggered by keyboard navigation): It is possible to disable this default behaviour by setting "pauseOnFocus" option to "false";
- Indicators are now focusable by default, since they are no longer simple list items, but buttons instead.
- Indicator text label (only detected by assistive technologies): It is possible to change the default …
> Slider accessibility

- docs/js/materialize.js
- js/global.js
- js/tabs.js
Title says all. All tests successful. Just a refactor and code reduction.
See #341
> Refactor tabs: cleaned code and removed jquery also removed hashing function

- Gruntfile.js
- src/global.ts
- webpack.config.js
Changed library export method to `export default M;` and the configuration of webpack output library to the options that has proved to work without breaking changes for existing doc pages and also for projects using the library in typescript classes and webpack for bundling.
- [x ] Bug fix (non-breaking change which fixes an issue).
- this can be tested with the webpack version of document that was linked in the issue description.
- It would be good to have some official demo of the library in a webpack project
- [x ] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x ] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pul …
> fix: library does not load in webpack projects #364

- src/autocomplete.ts
- src/buttons.ts
- src/cards.ts
- src/carousel.ts
- src/characterCounter.ts
- src/chips.ts
- src/collapsible.ts
- src/datepicker.ts
- src/dropdown.ts
- src/forms.ts
- src/global.ts
- src/materialbox.ts
- src/modal.ts
- src/parallax.ts
- src/pushpin.ts
- src/range.ts
- src/scrollspy.ts
- src/select.ts
- src/sidenav.ts
- src/slider.ts
- src/tabs.ts
- src/tapTarget.ts
- src/timepicker.ts
- src/toasts.ts
- src/tooltip.ts
- src/waves.ts
Replaced component instances "bound functions" by ES6 arrow expressions (instance functions which are already bound to current context) whenever it was possible, making the code cleaner and easier to maintain in the long term.
- Removed instance declarations of "bound functions";
- Updated declarations of handler functions.
Extra: Removed unnecessary spaces and "fixed" code indentation.
> Replace bound functions

- pug/contents/text_inputs_content.html
- src/forms.ts
- src/global.ts
- tests/spec/forms/formsFixture.html
- tests/spec/forms/formsSpec.js
This commit aims to restore "textareaAutoResize" method to the global scope and, therefore, should fix #362.
It has been exposed a little bit differently from v1.x, since it is no longer available as "`M.textareaAutoResize`", but `M.Forms.textareaAutoResize`, but it should not be an issue, since the docs have also been updated 😄.
Additional contributions:
- JSDoc added to method definition;
- Added test suites for "Forms" class methods.
> Restore form functions

- docs/js/init.js
- pug/contents/text_inputs_content.html
- src/characterCounter.ts
- tests/spec/forms/formsFixture.html
- tests/spec/forms/formsSpec.js
As discussed in [RFC#380](https://github.com/materializecss/materialize/discussions/380), this PR aims to replace the "`data-length`" attribute of "`CharacterCounter`" by the standard "`maxlength`" attr.
Highlights:
- CharacterCounter must use "maxlength" attribute to build a limited counter ("data-length") has been deprecated;
- Added test suites to CharacterCounter component;
- Updated docs:
-  Initialization (updated sample that was using jQuery);
- Added "breaking change" notice to "Character counter" section;
- Updated references from "data-length" to "maxlength";
- Updated initialization script.
Here is an example of working instances of "CharacterCounter".
> Replace character counter "data-length" attribute

- pug/contents/autocomplete_content.html
- src/autocomplete.ts
The current implementation of "onSearch" callback considers every option element when filtering, which causes undesired options to be displayed for autocompletion (see attached screenshots).
This PR aims to replace the current standard search function that should consider only the "id" and "text" attributes, if available, when filtering the given options.
Summary:
- Enhancements in standard search function:
- It now considers only the "id" and "text" attributes;
- Localized "lowercase" (better internationalization);
- Standard search still does not takes "text" into consideration if it is not provided;
- Reduced algorithmic complexity (no longer makes two iterations over the array and does not consider every option entry).
- Docs:
- Removed references to "old data type";
- Added …
> Replacement for standard search function in autocomplete

- sass/components/_theme_variables.scss
Made "CSS" variables compatible with custom elements (shadow dom).
This PR aims to close #329.
It is possible to check the current behaviour in [this pen](https://codepen.io/Canabale/pen/jOQWEzK) provided at #329.
With this "fix", the inputs should render correcly:
> Support to "Shadow DOM"

- pug/contents/text_inputs_content.html
- sass/components/forms/_input-fields.scss
Fix textarea padding which is currently not being inherited from "default input styles".
The textarea content is being currently overlaped by its label when not active and zero-padded in every context (focused/not focused).
Summary:
- Fixed stylesheet rules (`padding` in `materialize-texarea` class);
- Added new sample for textarea with custom placeholder;
- Added placeholder for textarea samples (enable floating label).
Focused:
Not focused:
Focused:
Not focused:
> Fix textarea padding

- sass/components/_pulse.scss
Pulse will no longer receive pointer events:
- Pulse will only act as a decorative element.
This should close #326.
Screenshots already provided in #326.
> fix(pulse): decorative pulse

- sass/components/_navbar.scss
Fix navbar dropdown menu that isn't properly styled
Fixes #410 
- [x ] Bug fix (non-breaking change which fixes an issue).
- [x ] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
- [x ] My commit messages follows the [conventional commit format](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md#submitting-your-pull-request)
- [ x] All new and existing tests passed.
> fix(navbar-dropdown): fix styling of dropdown menu in navbar

- pug/contents/helpers_content.html
- sass/components/_global.scss
#408 
New spacing helper SCSS classes for adding margin and padding to any element. The classes have the same utilization as the tailwind classes counterpart: with a combination of prefix, infix and suffix to create all the cardinal spacing combinations. The documentation was updated accordingly with tables explaining all the prefixes, infixes, suffixes and all the posible combinations in the helpers html page.
> Spacing helper classes

- pug/contents/text_inputs_content.html
- src/forms.ts
The current Forms.Init() function creates a DOMContentLoaded event which, when fired, will initialize the textareas and File Input Path present when the dom is loaded.
This mean that if we create a texarea programmatically, calling the Forms.Init() function will do nothing on the new created textarea.
We currently have no way to call the js code needed to initiate the textarea using the available functions.
That Pull request add the functions that will allow us to initialize the textarea and the File Input Path created programmatically.
> Add functions to initialize textarea and the File Input Path created programmatically

- src/datepicker.ts
When you select a different month or year in the date picker dropdown, it does not actually change the calendar to that month or year. This PR fixes that bug. Issue #412 
Original: https://jsfiddle.net/SeCrEt_BoY/m50y8Lq3/8/
After Fix: https://jsfiddle.net/abhigyanghosh30/odushvaz/32/
> fix(datepicker): Date picker didnot change calendar when selecting month or year from dropdown

- pug/contents/tooltips_content.html
- src/tooltip.ts
Alternative solution to "[Bug]: Toast html/unsafeHtml not work #394 ". This will allow to specify some element as tooltip content. A new property `data-tooltip-id `will allow specify an element as tooltip content instead of text.
will appear as
- [ x I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/main/CONTRIBUTING.md)**.
> Tooltip content

- src/tabs.ts
This check is done in other places. Avoids problems when using tabs without automatic content selection.
> very small fix for tabs: check for null content

- src/dropdown.ts
fix bug causing menu to toggle #456 
Either this PR or PR #452 should be merged; probably not both
- Fix a bug where multiple clicks on a dropdown trigger would cause the dropdown to open/close on the 2nd+ clicks
- Behaviour would also occur for the select component whichleveragesthe dropdown component
- Special consideration was given to the scenario where a select component has a label; where upon clicking the label the dropdown's _handleClick would be called, but the click event would not contain the dropdown-trigger (which is the select). Which would previously call both the _handleClick and _handleDocumentClick functions causing the same open/close behaviour
> fixes #456 dropdown open/close bug

- src/collapsible.ts
fix bug causing collapsible to not auto open
- Can't exactly explain why it was doing this, but in my development today I noticed that some of my non-accordion collapsibles weren't having their li's with class="active" set on them opening by default. Played around with the code a bit and found that putting these brackets back seemed to resolve it, so here we are
> fix: class="active" non-accordion collapsible not opening by default

- src/forms.ts
- tests/spec/forms/formsSpec.js
fixes https://github.com/materializecss/materialize/issues/446
resize textarea should work without explicit initialization
> fix: #446 Textarea not autoresize bug

- sass/components/_chips.scss
This is a minor but suitable change which updates the width property of an input field for adding new chips from fixed 120px to fit-content, with same !important weight. Also, the min-width and max-width properties are set to limit its size between 100px and 200px. With this change, the input placeholder (if limited to under 200px) will not get cropped, and it will also have a better fit into the input field, thereby offering it more flexibility to adapt the content.
Note: It was proposed long back into the parent repository https://github.com/Dogfalo/materialize/pull/6567, where it went approved but unattended. Today, after a few years, as I had noted that this forked repository from the parent repository is the one under the latest maintenance, I had …
> Updates input width in _chips.scss sass component

- sass/components/forms/_input-fields.scss
- src/datepicker.ts
Implemented HTML5 input date field support, making use of the input date field would enhance accessibility and follows the [RFC 3339 specification](https://www.rfc-editor.org/rfc/rfc3339)
> (fix/enhancement) Datepicker date type #230

- src/dropdown.ts
Dropdown component missing aria-expanded state, this causes a reduction in exposure to the web accessibility API, see #229
Implemented aria-expanded to initiator, open and close methods
> fix(Dropdown): accessibility - implemented aria-expanded #229

- src/dropdown.ts
Since the dropdown content is currently being appended to the container element of the latest triggering element, the dropdown content might get appended to a container that is currently in invisible state, this happens in the context where the dropdown component has multiple trigger elements, where triggering elements containers might become invisible because of a toggling visibility state (tabbable content, expandables, media queries, ...)
Updated the dropdown content to be attached to the current clicked/hovered triggering element
[Example of bug using a dropdown in nav/sidenav
](https://codepen.io/Geert-Selderslaghs/pen/JjgWXeW)
[Example of bug using a dropdown with multiple triggers in tabs context
](https://codepen.io/Geert-Selderslaghs/pen/gOVeLJq)
> (fix) Dropdown menu visibility #515

- sass/components/_timepicker.scss
- src/timepicker.ts
Fixes & enhancements based on https://github.com/materializecss/materialize/issues/476
- [] My change requires a change to the documentation, and updated it accordingly.
> Timepicker accessibility #476

- sass/components/_timepicker.scss
- src/timepicker.ts
This PR fixes issue as described in [this comment](https://github.com/materializecss/materialize/pull/520#issuecomment-2476389819) in #476 
Additional styling improvements have been applied as described in the Material guidelines, this applies mainly to margins/paddings, the addition of a button class to the am/pm buttons and usage of button-filled state instead of applying text-primary class on am/pm select
**Before**
**After**
> Timepicker accessibility

- sass/components/_tabs.scss
- src/tabs.ts
Adding the options to include icons to tabs.
Changes:
- css rules for vertial and horizontal text positions
- fix for a small issue of tab not being selected when the icon was clicked.
- updated documentation (in a separated PR in materialize-docs)
Note:
Following [M3 Tabs specification](https://m3.material.io/components/tabs/overview), tabs appear vertically-centered by default.
> Tabs with Icons

- sass/components/_datepicker.scss
Added additional CSS specs to fix month and year overflow issue as described in #512
> fix(Datepicker): text overflow - month and year not fully visible

- spec/tests/carousel/carouselSpec.js
- src/carousel.ts
Implemented keyboard accessibility on indicators #546
> accessibility(Carousel) indicators not accessible by keyboard interaction

- sass/components/_chips.scss
- spec/tests/chips/chipsSpec.js
- src/chips.ts
Enhancement proposal as described in #527
- Allow building up the chips container without constructing the input field, as result the grid styling would always be applied
- Implement the rendering of the input element as option within the Chips component
Todo:
> fix/improvement(Chips) - Input option (proof-of-concept)

- sass/components/_datepicker.scss
- spec/tests/datepicker/datepickerSpec.js
- src/datepicker.ts
**Implemented date range select functionality as per pull-request #360** 
- This functionality adds an end date field when option `dateRange: true` is provided
- Implemented calendar modal functionality to select an end date
- Implemented end field input change handling and modifiers to adjust the year, month and day selectors if a click or enter keypress interaction is executed
- Daterange classes added for in-range days
_styling of the in-range items needs to be addressed, propose create this in a new issue since the global layout of the datepicker is outdated: currently still follows the M2 guidelines_
> enhancement(Datepicker) date range

- eslint.config.mjs
- src/autocomplete.ts
- src/buttons.ts
- src/carousel.ts
- src/characterCounter.ts
- src/chips.ts
- src/component.ts
- src/datepicker.ts
- src/dropdown.ts
- src/forms.ts
- src/index.ts
- src/materialbox.ts
- src/parallax.ts
- src/pushpin.ts
- src/scrollspy.ts
- src/select.ts
- src/sidenav.ts
- src/slider.ts
- src/tabs.ts
- src/timepicker.ts
- src/toasts.ts
- src/tooltip.ts
- src/utils.ts
Follow up of issue #506 
Additional changes based on es coding standards configuration pull request #534, except for components where currently still are pull-requests open
There are still additional todo's regarding `@typescript-eslint/no-explicit-any` as I am looking for the correct type to declare on elements like `(this.el as any).M_<componentName>`, any suggestions on this one?
Guess we'll have two options to let the eslint pass:
- apply the correct types
- set `@typescript-eslint/no-explicit-any` to `warning` instead of `error` and create an additional issue to handle this in the future
Todo's:
> Eslint coding standards

- src/utils.ts
This is a proof-of-concept for #570
Implemented confirmation container util with callback functions so it's reusable among other components
Example of creating a single button with callback method:
```
Utils.createButton(
'.container', // container to append to
'Label', // button label 
['teal', 'btn-large'], // additional classes
true, // visibility
callback // callback method
);
```
Example of creating a confirmation container:
```
Utils.createConfirmationContainer(
'.container', // container to append to
'Confirm', // button label
'Cancel', // button label
confirm, // confirm callback
cancel // cancel callback
);
```
> enhancement(Utils) implemented confirmation container util methods

- sass/components/_datepicker.scss
- spec/tests/datepicker/datepickerSpec.js
- src/datepicker.ts
This issue is a follow up of #558, making great steps towards a M3 compatible datepicker
**Changelog**
Removed all modal related selectors #525 
Refactored styling, removed flex row styling so left face gets on top #558 
Refactored tag selectors to class selectors since it has advantages on specificity #558 
Implemented date range styling #360 
Implemented ability to use user defined end date input field via option `dateRangeEndEl: <selector>` #360 
Implemented option `openByDefault` #558 
Implemented input field interaction callback function #525 
Implemented functionality to render date format below the field in the input field supporting text section #558
**Todos**
Handling toggling visibility of the docked picker since open and close is deprecated since v2.2.1 and the event handlers …
> enhancement(Datepicker) styling refactor

- sass/components/_timepicker.scss
- src/timepicker.ts
Updated timepicker styling towards Material M3 standards #558 
Removed all modal related wrappers and selectors
Implemented m3 theme vars
Refactored positioning, replaced relative and absolute properties with flex
Implemented additional accessibility
> enhancement(Timepicker) styling updates

- sass/components/_timepicker.scss
- src/timepicker.ts
- src/utils.ts
This pull request is a follow up of #572 and #574 and handles the implementation of the Utils.createButton with callback method and the Utils.createConfirmContainer with callback methods
With the callback function, we can open and close modal (or custom) implementation in combination with timepicker with the onDone and onCancel callbacks
Example:
html
```
<div class="row">
<div class="input-field datepicker-field s12">
<input id="timepicker" type="text" class="timepicker">
<label for="timepicker">Time</label>
</div>
</div>
<dialog class="modal" style="width: 620px"></dialog>
```
script
```
M.Timepicker.init(document.querySelectorAll('.timepicker'), {
autoSubmit: false,
container: '.modal',
onInputInteraction: () => {
toggleModal();
},
onDone: () => {
toggleModal();
},
onCancel: () => { …
```
> enhancement(Timepicker) implementation with confirmation buttons util

- sass/components/_buttons.scss
- sass/components/mixins.module.scss
- sass/materialize.scss
Refactored buttons styling with scss mixin, to make it reusable in #565 #566
> refactor(Buttons) implement buttons styling with mixin

- sass/components/_buttons.scss
- sass/components/_cards.scss
- sass/components/mixins.module.scss
- sass/materialize.scss
- src/cards.ts
- src/index.ts
Implemented changes as described in #565
Updated cards components to initialize if not initialized manually, fixes[issuecomment#539](https://github.com/materializecss/materialize/issues/539#issuecomment-2564323612)
> enhancement(Cards) buttons mixin implementation + auto init

- sass/components/_buttons.scss
- sass/components/_global.scss
- sass/components/_pagination.scss
- sass/components/mixins.module.scss
- sass/materialize.scss
Created component styling file for pagination and included scss button styling mixin as described in #566
> enhancement(Pagination) buttons mixin

- sass/components/_cards.scss
This fixes a backwards compatibility issue where activator is set directly on the image, after #555 the card content renders empty if using activator on image instead of div
> fix(Cards) activator styling fix

- src/select.ts
This change resolves issue materializecss#510 by assigning the tabIndex value from the native select element to the input element created during initialization.
> fix(Select) preserve native select tabIndex value

- sass/components/mixins.module.scss
A text button with either `btn text` or `btn-flat` has a border. During the move to mixins a `border: none` got lost.
> fix(mixins): border none is missing from new button mixin

- sass/components/_navbar.scss
The use of `.nav` for navbar is inconsistent. If we use `.nav`, we should use it consistent.
n/a
> fix(_navbar): use .nav instead of nav 

- sass/components/forms/_input-fields.scss
Includes nested .inline class for .input-fields class elements.
Closes #606
> fix(_input-fields): display inline inputs fields actually inline

- sass/components/forms/_range.scss
Fixes not displaying range bar in Chrome browser.
Closes #609
> fix(_range): display bar for range in chrome browser

- components/dialog/readme.md
- components/divider/readme.md
Changing the structure, and put components into seperate folder. Later we can also make submodules out of each component. I think this is a cleaner approach and makes life easier.
What do you think?
> Seperate components into folders

- sass/components/forms/_checkboxes.scss
Gray out disabled checkbox as defined in [Material 3](https://m3.material.io/components/radio-button/specs)
I also update docs to cover all the scenarios as you can see on the screenshot.
> fix(_checkboxes): gray out when disabled

- sass/components/forms/_radio-buttons.scss
Gray out disabled radio button as defined in [Material 3](https://m3.material.io/components/radio-button/specs)
> fix(_radio-buttons): gray out when disabled

- .gitignore
- .storybook/main.ts
- .storybook/material-icons.css
- .storybook/preview.ts
- components/buttons/_buttons.scss
- components/buttons/buttons.stories.ts
- components/checkbox/checkbox.mdx
- components/checkbox/checkbox.stories.ts
- components/radio-button/radio-buttons.mdx
- components/radio-button/radio-buttons.stories.ts
- eslint.config.mjs
- package.json
- sass/mixins.module.scss
Hi, this is an example of how a Storybook can be used in this project. We use it heavily for our development and it offers great features:
- live preview of the components during development + light & dark theme
- ablity to document components in MDX
- allows for scripted 'play' tests similar to Jasmine
- allow to use chromatic to compare visual changes
Please check this and let me know what you think about it.
===========
An update - I added stories and documentation pages for radio button, check box and buttons. The branch also includes small fix to button's styling - see the before (left) and after (right) on screen shots below. 
The pull request is now ready for merge if approved. 
Preview of button stories to test as many as possible configurations:
See before on the left and after …
> Enhancement(Add Storybook)

- components/search/autocomplete.ts
Implemented data key on top of options data key, fixes changing selected option afterwards by restoring the menu items to the initial data
Removed method invokation that prevented text field from being updated
Fixes #624
> fix(Autocomplete) refactored options data to set on autocomplete object
