materializecss/materialize

- jade/getting_started/getting_started_content.html
> Update organization github star button

- .travis.yml
Travis build failed in https://github.com/materializecss/materialize/commit/585245b60a087d9653c61987cabea9c077acd8d2 because of updating `grunt-legacy-log-utils`. We have two choices, downgrade `grunt-legacy-log-utils` or update Node.js, then I choose update Node.js on travis because [6.x supports already ended in April 2019](https://aws.amazon.com/jp/blogs/developer/node-js-6-is-approaching-end-of-life-upgrade-your-aws-lambda-functions-to-the-node-js-10-lts/).
Additionally, remove the unnecessary task installing grunt-cli.
> Update Node.js version (using current LTS) for Travis CI

- jade/page-contents/sidenav_content.html
- js/sidenav.js
- sass/components/_sidenav.scss
The sidebar is draggable for mobile, but when I actually operate it on my smartphone, it is a little difficult to start dragging it. Therefore, I added an option it would be possible to adjust the width of the druggable area.
> Add dragTargetWidth option

- jade/page-contents/floating-action-button-content.html
This PR fixes a typo in the documentation about the floating action button. (dogfalo/materialize#6334)
> Fixed a typo in documentation about floating action button.

- .github/workflows/docs.yml
- .github/workflows/nightly.yml
> fix: :hammer: fix #88

- Gruntfile.js
- README.md
- docs/js/search.js
- extras/noUiSlider/nouislider.css
- extras/noUiSlider/nouislider.js
- jade/_navbar.jade
- jade/index/index_content.html
- package.json
- templates/masonry-template/index.html
- templates/masonry-template/preview.html
- templates/parallax-template/index.html
- templates/parallax-template/preview.html
- templates/starter-template/index.html
- templates/starter-template/preview.html
- test/html/tabs.html
> fix: 🔨 fix broken links (Closes #83)

- sass/components/_global.scss
- sass/components/_typography.scss
- sass/components/_variables.scss
> Fix breakpoint issue and incorrect min-width size

- jade/getting_started/getting_started_content.html
Hello. Just a small grammar change here regarding Bower. I didn't think it made sense to have it in parentheses, after a sentence, and not capitalized. It's not quite wrong as a second sentence, but it looks a bit awkward.
- [x ] Bug fix (non-breaking change which fixes an issue).
- [x ] I have read the **[CONTRIBUTING document](https://github.com/materializecss/materialize/blob/master/CONTRIBUTING.md)**.
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.
> grammar fix

- Gruntfile.js
- package-lock.json
- package.json
- sass/components/_badges.scss
- sass/components/_buttons.scss
- sass/components/_dropdown.scss
- sass/components/_grid.scss
- sass/components/_sidenav.scss
- sass/components/_typography.scss
- sass/components/_variables.scss
- sass/components/forms/_input-fields.scss
Closes #147. This also fixes 15 vulnerabilities (6 moderate, 7 high, 2 critical)
> build(deps): update deps and fix deprecation warning in sass files

- js/dropdown.js
Fixes a long requested Bug for iOS Touch devices with a provided and tested Patch.
For details see: #31
> fix: for iOS13 selecting wrong Dropdownitem on Touchdevices fix #31

- pug/page-contents/icons_content.html
- Add a link to searchable list for material-design-icons in the Icon description.
> fix: add link to searchable list #225

- sass/components/_waves.scss
- Remove extra indentation and trailing spaces which serve no purpose from _waves.scss.
> Remove extra indentation and trailing spaces

- CONTRIBUTING.md
- README.md
- extras/noUiSlider/nouislider.css
- templates/masonry-template/css/style.css
- templates/parallax-template/css/style.css
- test/html/autocomplete.html
- test/html/badges.html
- test/html/buttons.html
- test/html/cards.html
- test/html/carousel.html
- test/html/chips.html
- test/html/collapsible.html
- test/html/dropdown.html
- test/html/fixed_navbar.html
- test/html/forms.html
- test/html/materialbox.html
- test/html/multiple_modals.html
- test/html/multiple_sidenav.html
- test/html/overlayZindex.html
- test/html/pushpin.html
- test/html/scrollfire.html
- test/html/scrollspy.html
- test/html/select.html
- test/html/tabs.html
- test/html/toast.html
- test/html/tooltip.html
- test/html/waves.html
This is the 2nd PR for the missing commits from PR #271
Description from the original PR:
> Remove the unnecessary spaces, fix links url and add meta tags, minor typo fixes.
The original PR have (or had?) 4 commits, while this PR have one additional commit to fix wrong path for the materialize.js
> refactor: improve the documentation by gergo85

- Gruntfile.js
- pug/_navbar.pug
This fixes missing files that needs to be replaced when releasing new version
also:
* make the generated files copyright follow the current year
* fixes #312
N/A
> Fix missed files when replacing old version with new one

- CONTRIBUTING.md
- README.md
Just a quick doc fix. Title says it all ;)
> Documentation: renamed master to main and changed year

- pug/_head.pug
- pug/_scripts.html
Fix Links and put relative links for the css and js
> documentation links to relative links

- sass/components/_normalize.scss
> updated normalize.css v7.0.0  to 8.0.1 Issue##137

- pug/themes.pug
Small change in documentation to include 2 new added values.
Documentation.
> fix: updated themes variables in in documentation using previously defined values

- src/toasts.ts
> fix: toast not shows text when classes defined

- src/dropdown.ts
fixes #467 
retain dropdown position if the window is resized
> fix #467 dropdown + window resize bug

- src/materialbox.ts
Implemented tabindex, fixes Materialbox accessibility #246
> accessibility(Materialbox) tabindex

- sass/components/_collapsible.scss
Implemented changes as fix proposed in #448 
- Updated Collapsible header as icon was not well aligned
- Implemented additional header wrapper
- Updated positioning and margins between items
- Implemented Material expand icons
This change might need an update to documentation as additional content wrappers where added
- Collapsible header content wrapper: necessary for positioning of the elements
- Content displayed in a p tag adds margins automatically, no need to add additional wrappers here except in custom cases, what does not seem to be part of the Materialize framework
**Current**
```
<ul class="collapsible popout">
<li>
<div class="collapsible-header">
<i class="material-icons">filter_drama</i>
Title
</div>
<div class="collapsible-body">
<span>Content</span>
</div>
</li>
</ul>
``` …
> fix(Collapsible) styling

- sass/components/_cards.scss
- src/cards.ts
- src/index.ts
**Cards accessibility #539**
Refactored the Cards component component based in an object orientated manner
Implemented tab index and aria expanded to enhance accessibility
> accessibility(Cards) refactored component based, implemented tab index and aria expanded

- spec/tests/datepicker/datepickerSpec.js
- src/datepicker.ts
Implemented datepicker `isMultipleSelection` option as per #360
Allows user to select multiple dates on calendar, creates input fields based on selection and sets values in input fields
> enhancement(Datepicker) implemented multiselect

- sass/components/_buttons.scss
- sass/components/_tabs.scss
Implemented focus states, resolves #81
> accessibility(Tab & Button) implemented focus states

- sass/components/_datepicker.scss
Implemented styling for focus states on select elements #522
> accessibility(Datepicker) focus states
